apiVersion: project.openshift.io/v1
kind: Project
metadata:
  annotations:
    openshift.io/description: "welcome"
    openshift.io/display-name: "welcome"
    argocd.argoproj.io/sync-wave: "0"
  name: welcome
spec:
  finalizers:
  - kubernetes
