---
apiVersion: v1
kind: Namespace
metadata:
  name: welcome
  annotations:
    openshift.io/description: "welcome"
    openshift.io/display-name: "welcome"
    argocd.argoproj.io/sync-wave: "0"
spec: {}
