apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app: welcome
    app.kubernetes.io/instance: welcome
  name: welcome
spec:
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: welcome
